apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pico-api
  namespace: pico
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: pico-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
